# --- THÔNG TIN CƠ BẢN ---
title: Blog của Phạm Hữu Nam
description: >-
  Nơi chia sẻ những suy nghĩ, kỷ niệm và kiến thức lập trình.
author: Phạm Hữu Nam
email: your-email@example.com

# --- CẤU HÌNH ĐƯỜNG DẪN (QUAN TRỌNG) ---
# 1. url: Chỉ điền tên miền chính (KHÔNG có phần đuôi dự án)
url: "https://amno-o.github.io"

# 2. baseurl: Tên repo GitHub của bạn (Bắt buộc phải có dấu / ở đầu)
# Lưu ý: Khi chạy localhost, Jekyll sẽ tự bỏ qua cái này, nhưng lên GitHub thì CẦN nó.
baseurl: "/PHNam-s-chill-zone"

# --- CẤU HÌNH BUILD ---
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# --- PLUGINS ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --- LOẠI TRỪ ---
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
  - README.md